import JSZip from "jszip";

interface TypeLevel {
  name: string;
  size: string;
  weight: string;
  lineHeight: string;
  font: string;
}

interface Colors {
  bg: string;
  surface: string;
  textPrimary: string;
  textSecondary: string;
  accent: string;
  warning: string;
  success: string;
}

interface DesignState {
  projectName: string;
  spacingUnit: string;
  spacingScales: string;
  maxContentWidth: string;
  gridColumns: string;
  headingFont: string;
  bodyFont: string;
  typeLevels: TypeLevel[];
  colors: Colors;
  borderRadius: string;
  borderWidth: string;
  borderColor: string;
  selectedLayout: string;
  iconSource: string;
  iconLibrary: string;
  iconStyle: string;
  iconWeight: string;
  motionLevel: string;
  easingStyle: string;
  defaultDuration: string;
  hoverEffects: boolean;
  hoverStyle: string;
  dontList: string;
  breakpoints: string;
  mobileFirst: boolean;
  states: string;
}

function toKebab(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-");
}

function toCamel(name: string): string {
  return name
    .split(/\s+/)
    .map((w, i) => (i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()))
    .join("");
}

function colorsToVars(colors: Colors): string {
  return [
    `  --color-bg: ${colors.bg};`,
    `  --color-surface: ${colors.surface};`,
    `  --color-text-primary: ${colors.textPrimary};`,
    `  --color-text-secondary: ${colors.textSecondary};`,
    `  --color-accent: ${colors.accent};`,
    `  --color-warning: ${colors.warning};`,
    `  --color-success: ${colors.success};`,
  ].join("\n");
}

// ── tokens.css ──────────────────────────────────────────────────

function generateTokensCSS(s: DesignState): string {
  const spacings = s.spacingScales
    .split("/")
    .map((v) => v.trim())
    .filter(Boolean);

  const easing =
    s.easingStyle === "spring"
      ? "cubic-bezier(0.34, 1.56, 0.64, 1)"
      : s.easingStyle === "ease-out"
        ? "cubic-bezier(0.22, 1, 0.36, 1)"
        : s.easingStyle === "ease-in-out"
          ? "cubic-bezier(0.45, 0, 0.55, 1)"
          : "linear";

  const breakpoints = s.breakpoints
    .split("/")
    .map((v) => v.trim())
    .filter(Boolean);

  let css = `/* Design Tokens — ${s.projectName || "Untitled"} */\n`;
  css += `/* Generated by Design Token IDE */\n`;
  css += `/* TypeScript + CSS Variables */\n\n`;

  css += `:root {\n`;
  css += `  /* ── Typography ── */\n`;
  css += `  --font-heading: '${s.headingFont || "sans-serif"}', sans-serif;\n`;
  css += `  --font-body: '${s.bodyFont || "sans-serif"}', sans-serif;\n`;
  s.typeLevels.forEach((t) => {
    const key = toKebab(t.name);
    css += `  --type-${key}-size: ${t.size}px;\n`;
    css += `  --type-${key}-weight: ${t.weight};\n`;
    css += `  --type-${key}-line-height: ${t.lineHeight};\n`;
  });
  css += `\n`;

  css += `  /* ── Spacing ── */\n`;
  css += `  --space-unit: ${s.spacingUnit}px;\n`;
  spacings.forEach((sp, i) => {
    css += `  --space-${i + 1}: ${sp}px;\n`;
  });
  css += `  --max-content-width: ${s.maxContentWidth}px;\n`;
  css += `  --grid-columns: ${s.gridColumns};\n\n`;

  css += `  /* ── Border & Radius ── */\n`;
  css += `  --radius: ${s.borderRadius}px;\n`;
  css += `  --border-width: ${s.borderWidth}px;\n`;
  css += `  --border-color: ${s.borderColor};\n\n`;

  css += `  /* ── Motion ── */\n`;
  css += `  --duration: ${s.defaultDuration}ms;\n`;
  css += `  --easing: ${easing};\n\n`;

  // Colors
  css += `  /* ── Colors ── */\n`;
  css += colorsToVars(s.colors) + "\n";
  css += `}\n`;

  // Breakpoints as comments
  if (breakpoints.length > 0) {
    css += `\n/* ── Breakpoints (${s.mobileFirst ? "mobile-first" : "desktop-first"}) ── */\n`;
    breakpoints.forEach((bp, i) => {
      css += `/* --breakpoint-${i + 1}: ${bp}px */\n`;
    });
  }

  // Constraints as comments
  if (s.dontList.trim()) {
    css += `\n/* ── Constraints ── */\n`;
    s.dontList.split("\n").filter(Boolean).forEach((line) => {
      css += `/* ✗ ${line.trim()} */\n`;
    });
  }

  return css;
}

// ── tokens.ts ───────────────────────────────────────────────────

function generateTokensTS(s: DesignState): string {
  const spacings = s.spacingScales
    .split("/")
    .map((v) => v.trim())
    .filter(Boolean);

  const levelNames = s.typeLevels.map((t) => toCamel(t.name));

  let ts = `// Design Tokens — ${s.projectName || "Untitled"}\n`;
  ts += `// Generated by Design Token IDE\n\n`;

  // Type levels union
  ts += `export type TypeLevel = ${levelNames.map((n) => `"${n}"`).join(" | ")};\n\n`;

  // Spacing
  ts += `export const spacing = {\n`;
  ts += `  unit: ${s.spacingUnit},\n`;
  spacings.forEach((sp, i) => {
    ts += `  s${i + 1}: ${sp},\n`;
  });
  ts += `} as const;\n\n`;

  // Typography
  ts += `export const typography: Record<TypeLevel, {\n`;
  ts += `  size: number;\n  weight: number;\n  lineHeight: number;\n  font: "heading" | "body";\n`;
  ts += `}> = {\n`;
  s.typeLevels.forEach((t) => {
    ts += `  ${toCamel(t.name)}: { size: ${t.size || 16}, weight: ${t.weight || 400}, lineHeight: ${t.lineHeight || 1.5}, font: "${t.font}" },\n`;
  });
  ts += `};\n\n`;

  // Layout
  ts += `export const layout = {\n`;
  ts += `  maxContentWidth: ${s.maxContentWidth},\n`;
  ts += `  gridColumns: ${s.gridColumns},\n`;
  ts += `  borderRadius: ${s.borderRadius},\n`;
  ts += `  borderWidth: ${s.borderWidth},\n`;
  ts += `  borderColor: "${s.borderColor}",\n`;
  ts += `};\n\n`;

  // Motion
  ts += `export const motion = {\n`;
  ts += `  level: "${s.motionLevel}",\n`;
  ts += `  duration: ${s.defaultDuration},\n`;
  ts += `  easing: "${s.easingStyle}",\n`;
  ts += `};\n\n`;

  // Breakpoints
  const bps = s.breakpoints.split("/").map((v) => v.trim()).filter(Boolean);
  ts += `export const breakpoints = [${bps.join(", ")}] as const;\n`;
  ts += `export const mobileFirst = ${s.mobileFirst};\n`;

  return ts;
}

// ── Text.tsx ────────────────────────────────────────────────────

function generateTextTSX(s: DesignState): string {
  const levels = s.typeLevels;
  const levelNames = levels.map((t) => toCamel(t.name));

  const defaultTags: Record<string, string> = {};
  levels.forEach((t) => {
    const name = toCamel(t.name);
    if (name.includes("display") || name.includes("heading")) defaultTags[name] = "h2";
    else if (name.includes("caption") || name.includes("label")) defaultTags[name] = "span";
    else defaultTags[name] = "p";
  });

  let code = `import React from "react";\n`;
  code += `import type { TypeLevel } from "./tokens";\n`;
  code += `import "./tokens.css";\n\n`;

  code += `interface TextProps {\n`;
  code += `  level?: TypeLevel;\n`;
  code += `  as?: keyof React.JSX.IntrinsicElements;\n`;
  code += `  children: React.ReactNode;\n`;
  code += `  className?: string;\n`;
  code += `  style?: React.CSSProperties;\n`;
  code += `}\n\n`;

  code += `const defaultTag: Record<TypeLevel, keyof React.JSX.IntrinsicElements> = {\n`;
  levelNames.forEach((name) => {
    code += `  ${name}: "${defaultTags[name] || "p"}",\n`;
  });
  code += `};\n\n`;

  code += `export function Text({ level = "body", as, children, className, style }: TextProps) {\n`;
  code += `  const Component = as || defaultTag[level];\n`;
  code += `  const font = level === ${levelNames.filter((n) => /display|heading|title|^h[1-6]$/i.test(n)).map((n) => `"${n}"`).join(" || level === ")} ? "var(--font-heading)" : "var(--font-body)";\n\n`;

  code += `  return (\n`;
  code += `    <Component\n`;
  code += `      className={className}\n`;
  code += `      style={{\n`;
  code += `        fontSize: \`var(--type-\${level}-size)\`,\n`;
  code += `        fontWeight: \`var(--type-\${level}-weight)\`,\n`;
  code += `        lineHeight: \`var(--type-\${level}-line-height)\`,\n`;
  code += `        fontFamily: font,\n`;
  code += `        color: "var(--color-text-primary)",\n`;
  code += `        margin: 0,\n`;
  code += `        ...style,\n`;
  code += `      }}\n`;
  code += `    >\n`;
  code += `      {children}\n`;
  code += `    </Component>\n`;
  code += `  );\n`;
  code += `}\n`;

  return code;
}

// ── Button.tsx ──────────────────────────────────────────────────

function generateButtonTSX(s: DesignState): string {
  let code = `import React from "react";\n`;
  code += `import "./tokens.css";\n\n`;

  code += `interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {\n`;
  code += `  variant?: "primary" | "secondary" | "ghost";\n`;
  code += `  size?: "sm" | "md" | "lg";\n`;
  code += `}\n\n`;

  code += `const base: React.CSSProperties = {\n`;
  code += `  borderRadius: "var(--radius)",\n`;
  code += `  fontFamily: "var(--font-body)",\n`;
  code += `  fontWeight: 500,\n`;
  code += `  cursor: "pointer",\n`;
  code += `  transition: \`all var(--duration) var(--easing)\`,\n`;
  code += `  border: "none",\n`;
  code += `  display: "inline-flex",\n`;
  code += `  alignItems: "center",\n`;
  code += `  justifyContent: "center",\n`;
  code += `  gap: "var(--space-1)",\n`;
  code += `};\n\n`;

  code += `const sizes: Record<string, React.CSSProperties> = {\n`;
  code += `  sm: { padding: "calc(var(--space-1) / 2) var(--space-1)", fontSize: 13 },\n`;
  code += `  md: { padding: "var(--space-1) var(--space-2)", fontSize: 14 },\n`;
  code += `  lg: { padding: "var(--space-2) var(--space-3)", fontSize: 16 },\n`;
  code += `};\n\n`;

  code += `const variants: Record<string, React.CSSProperties> = {\n`;
  code += `  primary: {\n`;
  code += `    background: "var(--color-accent)",\n`;
  code += `    color: "#fff",\n`;
  code += `  },\n`;
  code += `  secondary: {\n`;
  code += `    background: "transparent",\n`;
  code += `    color: "var(--color-text-primary)",\n`;
  code += `    border: "var(--border-width) solid var(--border-color)",\n`;
  code += `  },\n`;
  code += `  ghost: {\n`;
  code += `    background: "transparent",\n`;
  code += `    color: "var(--color-accent)",\n`;
  code += `  },\n`;
  code += `};\n\n`;

  code += `export function Button({\n`;
  code += `  variant = "primary",\n`;
  code += `  size = "md",\n`;
  code += `  style,\n`;
  code += `  children,\n`;
  code += `  ...props\n`;
  code += `}: ButtonProps) {\n`;
  code += `  return (\n`;
  code += `    <button\n`;
  code += `      style={{ ...base, ...sizes[size], ...variants[variant], ...style }}\n`;
  code += `      {...props}\n`;
  code += `    >\n`;
  code += `      {children}\n`;
  code += `    </button>\n`;
  code += `  );\n`;
  code += `}\n`;

  return code;
}

// ── Card.tsx ────────────────────────────────────────────────────

function generateCardTSX(s: DesignState): string {
  let code = `import React from "react";\n`;
  code += `import "./tokens.css";\n\n`;

  code += `interface CardProps {\n`;
  code += `  thumbnail?: string;\n`;
  code += `  title?: string;\n`;
  code += `  caption?: string;\n`;
  code += `  children?: React.ReactNode;\n`;
  code += `  className?: string;\n`;
  code += `  style?: React.CSSProperties;\n`;
  code += `  onClick?: () => void;\n`;
  code += `}\n\n`;

  code += `export function Card({ thumbnail, title, caption, children, className, style, onClick }: CardProps) {\n`;
  code += `  return (\n`;
  code += `    <div\n`;
  code += `      className={className}\n`;
  code += `      onClick={onClick}\n`;
  code += `      style={{\n`;
  code += `        background: "var(--color-surface)",\n`;
  code += `        borderRadius: "var(--radius)",\n`;
  code += `        border: "var(--border-width) solid var(--border-color)",\n`;
  code += `        overflow: "hidden",\n`;
  code += `        transition: \`all var(--duration) var(--easing)\`,\n`;
  code += `        cursor: onClick ? "pointer" : "default",\n`;
  code += `        ...style,\n`;
  code += `      }}\n`;
  code += `    >\n`;
  code += `      {thumbnail && (\n`;
  code += `        <div\n`;
  code += `          style={{\n`;
  code += `            width: "100%",\n`;
  code += `            aspectRatio: "${s.iconWeight ? "16/9" : "16/9"}",\n`;
  code += `            background: \`url(\${thumbnail}) center/cover\`,\n`;
  code += `          }}\n`;
  code += `        />\n`;
  code += `      )}\n`;
  code += `      <div style={{ padding: "var(--space-2)" }}>\n`;
  code += `        {title && (\n`;
  code += `          <h3 style={{\n`;
  code += `            fontFamily: "var(--font-heading)",\n`;
  code += `            fontSize: "var(--type-heading-size, 18px)",\n`;
  code += `            fontWeight: "var(--type-heading-weight, 600)",\n`;
  code += `            color: "var(--color-text-primary)",\n`;
  code += `            margin: "0 0 var(--space-1) 0",\n`;
  code += `          }}>{title}</h3>\n`;
  code += `        )}\n`;
  code += `        {caption && (\n`;
  code += `          <p style={{\n`;
  code += `            fontFamily: "var(--font-body)",\n`;
  code += `            fontSize: "var(--type-caption-size, 13px)",\n`;
  code += `            color: "var(--color-text-secondary)",\n`;
  code += `            margin: 0,\n`;
  code += `          }}>{caption}</p>\n`;
  code += `        )}\n`;
  code += `        {children}\n`;
  code += `      </div>\n`;
  code += `    </div>\n`;
  code += `  );\n`;
  code += `}\n`;

  return code;
}

// ── Section.tsx ─────────────────────────────────────────────────

function generateSectionTSX(s: DesignState): string {
  let code = `import React from "react";\n`;
  code += `import "./tokens.css";\n\n`;

  code += `interface SectionProps {\n`;
  code += `  children: React.ReactNode;\n`;
  code += `  className?: string;\n`;
  code += `  style?: React.CSSProperties;\n`;
  code += `  fullWidth?: boolean;\n`;
  code += `}\n\n`;

  code += `export function Section({ children, className, style, fullWidth }: SectionProps) {\n`;
  code += `  return (\n`;
  code += `    <section\n`;
  code += `      className={className}\n`;
  code += `      style={{\n`;
  code += `        width: "100%",\n`;
  code += `        maxWidth: fullWidth ? "none" : "var(--max-content-width)",\n`;
  code += `        marginInline: "auto",\n`;
  code += `        paddingBlock: "var(--space-3)",\n`;
  code += `        paddingInline: "var(--space-2)",\n`;
  code += `        boxSizing: "border-box",\n`;
  code += `        ...style,\n`;
  code += `      }}\n`;
  code += `    >\n`;
  code += `      {children}\n`;
  code += `    </section>\n`;
  code += `  );\n`;
  code += `}\n`;

  return code;
}

// ── zip & download ──────────────────────────────────────────────

export async function generateAndDownload(state: DesignState): Promise<void> {
  const zip = new JSZip();
  const folder = zip.folder("design-system")!;

  folder.file("tokens.css", generateTokensCSS(state));
  folder.file("tokens.ts", generateTokensTS(state));
  folder.file("Text.tsx", generateTextTSX(state));
  folder.file("Button.tsx", generateButtonTSX(state));
  folder.file("Card.tsx", generateCardTSX(state));
  folder.file("Section.tsx", generateSectionTSX(state));

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${(state.projectName || "design-system").toLowerCase().replace(/\s+/g, "-")}-components.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
