import JSZip from "jszip";
// @ts-ignore
import { DENSITY_PRESETS, SEMANTIC_LABELS } from "./spacingPresets";

// ── Types ────────────────────────────────────────────────────────

interface TypeLevel {
  name: string;
  size: string;
  weight: string;
  lineHeight: string;
  font: string;
}

interface Colors {
  bg: string;
  surface: string;
  textPrimary: string;
  textSecondary: string;
  accent: string;
  warning: string;
  success: string;
}

interface SpacingSemantic {
  inlineY: number;
  inlineX: number;
  content: number;
  element: number;
  block: number;
  section: number;
  page: number;
}

interface DesignState {
  projectName: string;
  maxContentWidth: string;
  headingFont: string;
  bodyFont: string;
  typeLevels: TypeLevel[];
  colors: Colors;
  density: string;
  borderRadius: string;
  borderWidth: string;
  borderColor: string;
  borderComponents: Record<string, boolean>;
  radiusOverrides: Record<string, string>;
  motionLevel: string;
  easingStyle: string;
  defaultDuration: string;
  hoverEffects: boolean;
  hoverStyle: string;
  dontList: string;
  breakpoints: string;
  mobileFirst: boolean;
  states: string;
  visitedSections: Record<string, boolean>;
  components: Record<string, any>;
}

// ── Helpers ──────────────────────────────────────────────────────

function toKebab(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-");
}

function toCamel(name: string): string {
  return name
    .split(/\s+/)
    .map((w, i) => (i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()))
    .join("");
}

function easingValue(style: string): string {
  if (style === "spring") return "cubic-bezier(0.34, 1.56, 0.64, 1)";
  if (style === "ease-out") return "cubic-bezier(0.22, 1, 0.36, 1)";
  if (style === "ease-in-out") return "cubic-bezier(0.45, 0, 0.55, 1)";
  return "linear";
}

function spacingOf(s: DesignState): SpacingSemantic {
  return (DENSITY_PRESETS[s.density || "balanced"] || DENSITY_PRESETS.balanced).semantic;
}


function visited(s: DesignState, key: string): boolean {
  return !!(s.visitedSections || {})[key];
}

function comp(s: DesignState, id: string): any {
  return (s.components || {})[id] || {};
}

function radiusNum(s: DesignState, compId?: string): number {
  if (compId && s.radiusOverrides?.[compId]) return parseInt(s.radiusOverrides[compId]);
  return parseInt(s.borderRadius) || 8;
}

function radiusVar(s: DesignState, compId?: string): string {
  if (compId && s.radiusOverrides?.[compId]) return `"var(--radius-${toKebab(compId)})"`;
  return `"var(--radius)"`;
}

function hasBorder(s: DesignState, compId: string): boolean {
  return !!(s.borderComponents || {})[compId];
}

const GENERIC_FONTS = ["serif", "sans-serif", "monospace", "cursive", "fantasy", "system-ui"];

function fontCSSValue(font: string): string {
  const f = font || "sans-serif";
  if (GENERIC_FONTS.includes(f.toLowerCase())) return f;
  return `'${f}', sans-serif`;
}

// ── CLAUDE.md ────────────────────────────────────────────────────

function generateClaudeMD(s: DesignState): string {
  const c = s.colors;
  const hFont = s.headingFont || "sans-serif";
  const bFont = s.bodyFont || "sans-serif";
  const sp = spacingOf(s);
  const icon = comp(s, "Icon");

  let md = `# Design System${s.projectName ? ` — ${s.projectName}` : ""}\n\n`;
  md += `Generated by Design Token IDE. This file instructs AI coding agents how to use this design system.\n\n`;

  // Quick start
  md += `## Quick Start\n\n`;
  md += `1. Import \`tokens.css\` at your app entry point (\`import "./design-system/tokens.css"\`)\n`;
  md += `2. Use components from \`primitives.tsx\`, \`blocks.tsx\`, \`sections.tsx\`\n`;
  md += `3. All styling uses CSS custom properties — never hardcode values\n\n`;

  // Rules
  md += `## Rules (MUST follow)\n\n`;
  md += `- **All colors** must use \`var(--color-*)\` CSS variables. NEVER hardcode hex values.\n`;
  md += `- **All fonts** must use \`var(--font-heading)\` or \`var(--font-body)\`. NEVER add custom font-family.\n`;
  md += `- **All spacing** must use \`var(--space-*)\` variables. NEVER use arbitrary pixel values.\n`;
  md += `- **Border radius** must use \`var(--radius)\` or component-specific radius variables.\n`;
  md += `- **Transitions** must use \`var(--duration)\` and \`var(--easing)\`.\n`;
  md += `- Do NOT use Tailwind's default color palette. Only use the CSS variables defined in tokens.css.\n`;
  md += `- When creating new components, follow the same patterns used in primitives/blocks/sections.\n\n`;

  // Colors
  md += `## Color System (7 semantic roles)\n\n`;
  md += `| Variable | Value | Usage |\n`;
  md += `|----------|-------|-------|\n`;
  md += `| \`--color-bg\` | \`${c.bg}\` | Page background, section backgrounds |\n`;
  md += `| \`--color-surface\` | \`${c.surface}\` | Card, Navbar, Footer, input backgrounds |\n`;
  md += `| \`--color-text-primary\` | \`${c.textPrimary}\` | Headings, nav links, button text |\n`;
  md += `| \`--color-text-secondary\` | \`${c.textSecondary}\` | Body text, captions, placeholders |\n`;
  md += `| \`--color-accent\` | \`${c.accent}\` | CTA buttons, links, badges, active states |\n`;
  md += `| \`--color-warning\` | \`${c.warning}\` | Warning indicators |\n`;
  md += `| \`--color-success\` | \`${c.success}\` | Success indicators |\n\n`;

  // Typography
  md += `## Typography\n\n`;
  md += `- **Heading font**: ${hFont}\n`;
  md += `- **Body font**: ${bFont}\n\n`;
  md += `| Level | Size | Weight | Line Height | Font |\n`;
  md += `|-------|------|--------|-------------|------|\n`;
  s.typeLevels.forEach(t => {
    md += `| ${t.name} | ${t.size}px | ${t.weight} | ${t.lineHeight} | ${t.font} |\n`;
  });
  md += `\n`;

  // Spacing
  md += `## Spacing & Layout\n\n`;
  md += `- Density: ${s.density || "balanced"}\n`;
  md += `- Max content width: \`--max-content-width\` = ${s.maxContentWidth === "full" ? "100%" : s.maxContentWidth + "px"}\n\n`;
  md += `| Variable | Value | Usage |\n`;
  md += `|----------|-------|-------|\n`;
  md += `| \`--space-inline-y\` | ${sp.inlineY}px | Button/Badge vertical padding |\n`;
  md += `| \`--space-inline-x\` | ${sp.inlineX}px | Button/Badge horizontal padding |\n`;
  md += `| \`--space-content\` | ${sp.content}px | Card/Section internal padding |\n`;
  md += `| \`--space-element\` | ${sp.element}px | Gap between title and body, icon and text |\n`;
  md += `| \`--space-block\` | ${sp.block}px | Gap between Cards, Gallery grid gap |\n`;
  md += `| \`--space-section\` | ${sp.section}px | Gap between page sections |\n`;
  md += `| \`--space-page\` | ${sp.page}px | Page margin, content to screen edge |\n\n`;

  // Border
  md += `## Borders & Radius\n\n`;
  md += `- Default radius: ${s.borderRadius}px\n`;
  md += `- Border width: ${s.borderWidth}px\n`;
  md += `- Border color: ${s.borderColor}\n\n`;

  // Motion
  md += `## Motion\n\n`;
  md += `- Duration: ${s.defaultDuration}ms\n`;
  md += `- Easing: ${s.easingStyle} → \`${easingValue(s.easingStyle)}\`\n\n`;

  // Icon
  if (visited(s, "comp-Icon")) {
    md += `## Icon System\n\n`;
    md += `- **Library**: ${icon.library || "Lucide"}\n`;
    md += `- **Style**: ${icon.style || "outline"}\n`;
    md += `- **Stroke weight**: ${icon.weight || "1.5"}\n`;
    md += `- Usage: Install \`${(icon.library || "Lucide").toLowerCase().replace(/\s/g, "-")}-react\` and import icons directly.\n`;
    md += `- No icon wrapper component is provided — use the library's components directly.\n\n`;
  }

  // Components
  md += `## Available Components\n\n`;

  const primComps: string[] = [];
  const blockComps: string[] = [];
  const sectionComps: string[] = [];

  if (visited(s, "comp-Button")) {
    const c = comp(s, "Button");
    primComps.push("Button");
    md += `### Button\n`;
    md += `- **File**: \`primitives.tsx\`\n`;
    md += `- **Variants**: ${(c.variants || ["primary", "secondary", "ghost"]).map((v: string) => `\`"${v}"\``).join(", ")}\n`;
    md += `- **Sizes**: ${(c.sizes || ["sm", "md", "lg"]).map((v: string) => `\`"${v}"\``).join(", ")}\n\n`;
  }

  if (visited(s, "comp-Text")) {
    const c = comp(s, "Text");
    primComps.push("Text");
    md += `### Text\n`;
    md += `- **File**: \`primitives.tsx\`\n`;
    md += `- **Variants**: ${(c.variants || ["paragraph"]).map((v: string) => `\`"${v}"\``).join(", ")}\n`;
    if ((c.variants || []).includes("blockquote")) {
      md += `- **Quote style**: \`"${c.quoteStyle || "border-left"}"\`\n`;
    }
    md += `\n`;
  }

  if (visited(s, "comp-Divider")) {
    primComps.push("Divider");
    md += `### Divider\n`;
    md += `- **File**: \`primitives.tsx\`\n`;
    md += `- **Style**: \`"${comp(s, "Divider").style || "line"}"\`\n\n`;
  }

  if (visited(s, "comp-Badge")) {
    primComps.push("Badge");
    md += `### Badge\n`;
    md += `- **File**: \`primitives.tsx\`\n`;
    md += `- **Variant**: \`"${comp(s, "Badge").variant || "filled"}"\`\n\n`;
  }

  if (visited(s, "comp-Avatar")) {
    const c = comp(s, "Avatar");
    primComps.push("Avatar");
    md += `### Avatar\n`;
    md += `- **File**: \`primitives.tsx\`\n`;
    md += `- **Shape**: \`"${c.shape || "circle"}"\`\n`;
    md += `- **Filter**: \`"${c.filter || "color"}"\`\n\n`;
  }

  if (visited(s, "comp-Card")) {
    const c = comp(s, "Card");
    blockComps.push("Card");
    md += `### Card\n`;
    md += `- **File**: \`blocks.tsx\`\n`;
    md += `- **Orientation**: \`"${c.orientation || "vertical"}"\`\n`;
    md += `- **Thumbnail ratio**: \`"${c.thumbnailRatio || "16:9"}"\`\n`;
    md += `- **Hover effect**: ${c.hoverEffect !== false ? "yes" : "no"}\n\n`;
  }

  if (visited(s, "comp-Gallery")) {
    const c = comp(s, "Gallery");
    blockComps.push("Gallery");
    md += `### Gallery\n`;
    md += `- **File**: \`blocks.tsx\`\n`;
    md += `- **Columns**: ${c.columns || 3}\n`;
    md += `- **Style**: \`"${c.style || "grid"}"\`\n\n`;
  }

  if (visited(s, "comp-Navbar")) {
    const c = comp(s, "Navbar");
    sectionComps.push("Navbar");
    md += `### Navbar\n`;
    md += `- **File**: \`sections.tsx\`\n`;
    md += `- **Layout**: \`"${c.layout || "logo-left"}"\`\n`;
    md += `- **Transparent**: ${c.transparent ? "yes" : "no"}\n\n`;
  }

  if (visited(s, "comp-Hero")) {
    const c = comp(s, "Hero");
    sectionComps.push("Hero");
    md += `### Hero\n`;
    md += `- **File**: \`sections.tsx\`\n`;
    md += `- **Visual type**: \`"${c.visualType || "illustration"}"\`\n`;
    if (c.visualNotes) md += `- **Visual notes**: ${c.visualNotes}\n`;
    md += `\n`;
  }

  if (visited(s, "comp-Footer")) {
    const c = comp(s, "Footer");
    sectionComps.push("Footer");
    md += `### Footer\n`;
    md += `- **File**: \`sections.tsx\`\n`;
    md += `- **Structure**: \`"${c.structure || "multi-column"}"\`\n`;
    md += `- **Newsletter**: ${c.hasNewsletter ? "yes" : "no"}\n\n`;
  }

  if (visited(s, "comp-CTA")) {
    sectionComps.push("CTA");
    md += `### CTA\n`;
    md += `- **File**: \`sections.tsx\`\n`;
    md += `- **Structure**: \`"${comp(s, "CTA").structure || "centered"}"\`\n\n`;
  }

  // Don'ts
  if (s.dontList && s.dontList.trim()) {
    md += `## Constraints (Do NOT)\n\n`;
    const cnToEn: Record<string, string> = {
      "不用渐变": "No gradients",
      "不用投影超过2层": "No more than 2 shadow layers",
      "不用超过2种字体": "No more than 2 font families",
      "不用纯黑 #000": "No pure black (#000)",
      "不用纯黑": "No pure black (#000)",
    };
    s.dontList.split("\n").filter(Boolean).forEach(line => {
      const trimmed = line.trim();
      const en = cnToEn[trimmed];
      md += en ? `- ✗ ${en} (${trimmed})\n` : `- ✗ ${trimmed}\n`;
    });
    md += `\n`;
  }

  return md;
}

// ── tokens.css ──────────────────────────────────────────────────

function generateTokensCSS(s: DesignState): string {
  const sp = spacingOf(s);
  const easing = easingValue(s.easingStyle);
  const hFont = s.headingFont || "sans-serif";
  const bFont = s.bodyFont || "sans-serif";

  // Google fonts import
  const googleFonts = [hFont, bFont]
    .filter(f => f && !["sans-serif"].includes(f))
    .map(f => f.replace(/ /g, "+"));
  const uniqueFonts = [...new Set(googleFonts)];

  let css = `/* Design Tokens — ${s.projectName || "Untitled"} */\n`;
  css += `/* Generated by Design Token IDE */\n\n`;

  if (uniqueFonts.length > 0) {
    css += `@import url('https://fonts.googleapis.com/css2?${uniqueFonts.map(f => `family=${f}:wght@300;400;500;600;700`).join("&")}&display=swap');\n\n`;
  }

  css += `:root {\n`;

  // Fonts
  css += `  /* ── Fonts ── */\n`;
  css += `  --font-heading: ${fontCSSValue(hFont)};\n`;
  css += `  --font-body: ${fontCSSValue(bFont)};\n\n`;

  // Typography levels
  css += `  /* ── Typography ── */\n`;
  s.typeLevels.forEach(t => {
    const key = toKebab(t.name);
    css += `  --type-${key}-size: ${t.size}px;\n`;
    css += `  --type-${key}-weight: ${t.weight};\n`;
    css += `  --type-${key}-line-height: ${t.lineHeight};\n`;
  });
  css += `\n`;

  // Colors
  css += `  /* ── Colors ── */\n`;
  css += `  --color-bg: ${s.colors.bg};\n`;
  css += `  --color-surface: ${s.colors.surface};\n`;
  css += `  --color-text-primary: ${s.colors.textPrimary};\n`;
  css += `  --color-text-secondary: ${s.colors.textSecondary};\n`;
  css += `  --color-accent: ${s.colors.accent};\n`;
  css += `  --color-warning: ${s.colors.warning};\n`;
  css += `  --color-success: ${s.colors.success};\n\n`;

  // Spacing — semantic tokens derived from density
  css += `  /* ── Spacing (density: ${s.density || "balanced"}) ── */\n`;
  css += `  --space-inline-y: ${sp.inlineY}px;\n`;
  css += `  --space-inline-x: ${sp.inlineX}px;\n`;
  css += `  --space-content: ${sp.content}px;\n`;
  css += `  --space-element: ${sp.element}px;\n`;
  css += `  --space-block: ${sp.block}px;\n`;
  css += `  --space-section: ${sp.section}px;\n`;
  css += `  --space-page: ${sp.page}px;\n`;
  css += `  --max-content-width: ${s.maxContentWidth === "full" ? "100%" : s.maxContentWidth + "px"};\n\n`;

  // Border & Radius
  css += `  /* ── Border & Radius ── */\n`;
  css += `  --radius: ${s.borderRadius}px;\n`;
  css += `  --border-width: ${s.borderWidth}px;\n`;
  css += `  --border-color: ${s.borderColor};\n`;
  // Per-component radius overrides
  const ro = s.radiusOverrides || {};
  for (const [compId, val] of Object.entries(ro)) {
    if (val) css += `  --radius-${toKebab(compId)}: ${val}px;\n`;
  }
  css += `\n`;

  // Motion
  css += `  /* ── Motion ── */\n`;
  css += `  --duration: ${s.defaultDuration}ms;\n`;
  css += `  --easing: ${easing};\n`;
  css += `}\n`;

  // Breakpoints
  const bps = s.breakpoints.split("/").map(v => v.trim()).filter(Boolean);
  if (bps.length > 0) {
    css += `\n/* ── Breakpoints (${s.mobileFirst ? "mobile-first" : "desktop-first"}) ── */\n`;
    bps.forEach((bp, i) => {
      css += `/* @custom-media --bp-${i + 1}: (${s.mobileFirst ? "min" : "max"}-width: ${bp}px) */\n`;
    });
  }

  return css;
}

// ── tokens.ts ───────────────────────────────────────────────────

function generateTokensTS(s: DesignState): string {
  const sp = spacingOf(s);

  let ts = `// Design Tokens — ${s.projectName || "Untitled"}\n`;
  ts += `// Generated by Design Token IDE\n\n`;

  // Colors
  ts += `export const colors = {\n`;
  ts += `  bg: "${s.colors.bg}",\n`;
  ts += `  surface: "${s.colors.surface}",\n`;
  ts += `  textPrimary: "${s.colors.textPrimary}",\n`;
  ts += `  textSecondary: "${s.colors.textSecondary}",\n`;
  ts += `  accent: "${s.colors.accent}",\n`;
  ts += `  warning: "${s.colors.warning}",\n`;
  ts += `  success: "${s.colors.success}",\n`;
  ts += `} as const;\n\n`;

  // Fonts
  ts += `export const fonts = {\n`;
  ts += `  heading: "${s.headingFont || "sans-serif"}",\n`;
  ts += `  body: "${s.bodyFont || "sans-serif"}",\n`;
  ts += `} as const;\n\n`;

  // Typography
  const levelNames = s.typeLevels.map(t => toCamel(t.name));
  ts += `export type TypeLevel = ${levelNames.map(n => `"${n}"`).join(" | ")};\n\n`;
  ts += `export const typography: Record<TypeLevel, {\n`;
  ts += `  size: number; weight: number; lineHeight: number; font: "heading" | "body";\n`;
  ts += `}> = {\n`;
  s.typeLevels.forEach(t => {
    ts += `  ${toCamel(t.name)}: { size: ${t.size || 16}, weight: ${t.weight || 400}, lineHeight: ${t.lineHeight || 1.5}, font: "${t.font}" },\n`;
  });
  ts += `};\n\n`;

  // Spacing
  ts += `export const spacing = {\n`;
  ts += `  inlineY: ${sp.inlineY},\n`;
  ts += `  inlineX: ${sp.inlineX},\n`;
  ts += `  content: ${sp.content},\n`;
  ts += `  element: ${sp.element},\n`;
  ts += `  block: ${sp.block},\n`;
  ts += `  section: ${sp.section},\n`;
  ts += `  page: ${sp.page},\n`;
  ts += `} as const;\n\n`;

  // Layout
  ts += `export const layout = {\n`;
  ts += `  maxContentWidth: ${s.maxContentWidth === "full" ? '"100%"' : s.maxContentWidth},\n`;
  ts += `  radius: ${s.borderRadius},\n`;
  ts += `  borderWidth: ${s.borderWidth},\n`;
  ts += `  borderColor: "${s.borderColor}",\n`;
  ts += `  density: "${s.density || "balanced"}",\n`;
  ts += `} as const;\n\n`;

  // Motion
  ts += `export const motion = {\n`;
  ts += `  level: "${s.motionLevel}",\n`;
  ts += `  duration: ${s.defaultDuration},\n`;
  ts += `  easing: "${s.easingStyle}",\n`;
  ts += `} as const;\n\n`;

  // Breakpoints
  const bps = s.breakpoints.split("/").map(v => v.trim()).filter(Boolean);
  ts += `export const breakpoints = [${bps.join(", ")}] as const;\n`;
  ts += `export const mobileFirst = ${s.mobileFirst};\n\n`;

  // Icon spec (if visited)
  if (visited(s, "comp-Icon")) {
    const icon = comp(s, "Icon");
    ts += `export const icon = {\n`;
    ts += `  library: "${icon.library || "Lucide"}",\n`;
    ts += `  style: "${icon.style || "outline"}",\n`;
    ts += `  weight: ${parseFloat(icon.weight) || 1.5},\n`;
    ts += `} as const;\n`;
  }

  return ts;
}

// ── primitives.tsx ──────────────────────────────────────────────

function generateButtonCode(s: DesignState): string {
  const btn = comp(s, "Button");
  const variants = btn.variants || ["primary", "secondary", "ghost"];
  const sizes = btn.sizes || ["sm", "md", "lg"];
  const hasBdr = hasBorder(s, "Button");
  const r = radiusVar(s, "Button");
  const bw = parseInt(s.borderWidth) || 1;

  let c = `// ── Button ──\n\n`;
  c += `interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {\n`;
  c += `  variant?: ${variants.map((v: string) => `"${v}"`).join(" | ")};\n`;
  c += `  size?: ${sizes.map((v: string) => `"${v}"`).join(" | ")};\n`;
  c += `}\n\n`;

  c += `const buttonBase: React.CSSProperties = {\n`;
  c += `  borderRadius: ${r},\n`;
  c += `  fontFamily: "var(--font-body)",\n`;
  c += `  fontWeight: 500,\n`;
  c += `  cursor: "pointer",\n`;
  c += `  transition: "all var(--duration) var(--easing)",\n`;
  c += `  border: "none",\n`;
  c += `  display: "inline-flex",\n`;
  c += `  alignItems: "center",\n`;
  c += `  justifyContent: "center",\n`;
  c += `};\n\n`;

  c += `const buttonSizes: Record<string, React.CSSProperties> = {\n`;
  if (sizes.includes("sm")) c += `  sm: { padding: "calc(var(--space-inline-y) * 0.5) var(--space-inline-x)", fontSize: 13 },\n`;
  if (sizes.includes("md")) c += `  md: { padding: "var(--space-inline-y) var(--space-inline-x)", fontSize: 14 },\n`;
  if (sizes.includes("lg")) c += `  lg: { padding: "calc(var(--space-inline-y) * 1.5) calc(var(--space-inline-x) * 1.5)", fontSize: 16 },\n`;
  c += `};\n\n`;

  c += `const buttonVariants: Record<string, React.CSSProperties> = {\n`;
  if (variants.includes("primary")) {
    c += `  primary: { background: "var(--color-accent)", color: "#fff" },\n`;
  }
  if (variants.includes("secondary")) {
    c += `  secondary: { background: "transparent", color: "var(--color-text-primary)"${hasBdr ? `, border: "${bw}px solid var(--border-color)"` : ""} },\n`;
  }
  if (variants.includes("ghost")) {
    c += `  ghost: { background: "transparent", color: "var(--color-accent)" },\n`;
  }
  c += `};\n\n`;

  c += `export function Button({ variant = "${variants[0]}", size = "${sizes.includes("md") ? "md" : sizes[0]}", style, children, ...props }: ButtonProps) {\n`;
  c += `  return (\n`;
  c += `    <button style={{ ...buttonBase, ...buttonSizes[size], ...buttonVariants[variant], ...style }} {...props}>\n`;
  c += `      {children}\n`;
  c += `    </button>\n`;
  c += `  );\n`;
  c += `}\n`;

  return c;
}

function generateTextCode(s: DesignState): string {
  const txt = comp(s, "Text");
  const variants = txt.variants || ["paragraph"];
  const quoteStyle = txt.quoteStyle || "border-left";

  let c = `// ── Text ──\n\n`;
  c += `interface TextProps {\n`;
  c += `  variant?: ${variants.map((v: string) => `"${v}"`).join(" | ")};\n`;
  c += `  children: React.ReactNode;\n`;
  c += `  style?: React.CSSProperties;\n`;
  c += `}\n\n`;

  c += `export function Text({ variant = "${variants[0]}", children, style }: TextProps) {\n`;

  if (variants.includes("blockquote")) {
    c += `  if (variant === "blockquote") {\n`;
    if (quoteStyle === "large-italic") {
      c += `    return <blockquote style={{ fontFamily: "var(--font-heading)", fontSize: 20, fontStyle: "italic", fontWeight: 500, color: "var(--color-text-primary)", padding: "var(--space-block) 0", margin: 0, ...style }}>{children}</blockquote>;\n`;
    } else if (quoteStyle === "centered") {
      c += `    return <blockquote style={{ fontFamily: "var(--font-heading)", fontSize: 16, fontStyle: "italic", color: "var(--color-text-primary)", textAlign: "center", padding: "var(--space-block) var(--space-content)", margin: 0, ...style }}>{children}</blockquote>;\n`;
    } else {
      c += `    return <blockquote style={{ fontFamily: "var(--font-body)", fontSize: 14, lineHeight: 1.7, color: "var(--color-text-primary)", borderLeft: "3px solid var(--color-accent)", paddingLeft: "var(--space-block)", margin: 0, ...style }}>{children}</blockquote>;\n`;
    }
    c += `  }\n`;
  }

  if (variants.includes("paragraph-sm")) {
    c += `  if (variant === "paragraph-sm") {\n`;
    c += `    return <p style={{ fontFamily: "var(--font-body)", fontSize: 12, lineHeight: 1.6, color: "var(--color-text-secondary)", margin: 0, ...style }}>{children}</p>;\n`;
    c += `  }\n`;
  }

  c += `  return <p style={{ fontFamily: "var(--font-body)", fontSize: 14, lineHeight: 1.7, color: "var(--color-text-primary)", margin: 0, ...style }}>{children}</p>;\n`;
  c += `}\n`;

  return c;
}

function generateDividerCode(s: DesignState): string {
  const divStyle = comp(s, "Divider").style || "line";
  const bw = parseInt(s.borderWidth) || 1;

  let c = `// ── Divider ──\n\n`;
  c += `export function Divider({ style }: { style?: React.CSSProperties }) {\n`;

  if (divStyle === "space") {
    c += `  return <div style={{ height: "var(--space-block)", ...style }} />;\n`;
  } else {
    const borderStyle = divStyle === "dashed" ? "dashed" : divStyle === "dot" ? "dotted" : "solid";
    c += `  return <hr style={{ border: "none", borderTop: "${bw}px ${borderStyle} var(--border-color)", margin: 0, ...style }} />;\n`;
  }

  c += `}\n`;
  return c;
}

function generateBadgeCode(s: DesignState): string {
  const variant = comp(s, "Badge").variant || "filled";
  const r = Math.min(radiusNum(s, "Badge"), 12);
  const hasBdr = hasBorder(s, "Badge");

  let c = `// ── Badge ──\n\n`;
  c += `export function Badge({ children, style }: { children: React.ReactNode; style?: React.CSSProperties }) {\n`;

  if (variant === "outline") {
    c += `  return (\n`;
    c += `    <span style={{ padding: "2px var(--space-inline-y)", borderRadius: ${r}, fontFamily: "var(--font-body)", fontSize: 11, fontWeight: 500, background: "transparent", color: "var(--color-accent)"${hasBdr ? `, border: "1px solid var(--color-accent)"` : ""}, ...style }}>\n`;
    c += `      {children}\n`;
    c += `    </span>\n`;
    c += `  );\n`;
  } else {
    c += `  return (\n`;
    c += `    <span style={{ padding: "2px var(--space-inline-y)", borderRadius: ${r}, fontFamily: "var(--font-body)", fontSize: 11, fontWeight: 500, background: "var(--color-surface)", color: "var(--color-accent)", ...style }}>\n`;
    c += `      {children}\n`;
    c += `    </span>\n`;
    c += `  );\n`;
  }

  c += `}\n`;
  return c;
}

function generateAvatarCode(s: DesignState): string {
  const av = comp(s, "Avatar");
  const shape = av.shape || "circle";
  const filter = av.filter || "color";
  const hasBdr = hasBorder(s, "Avatar");
  const bw = parseInt(s.borderWidth) || 1;
  const r = radiusVar(s, "Avatar");

  const borderRadius = shape === "circle" ? `"50%"` : shape === "rounded-square" ? r : `0`;
  const filterCSS = filter === "grayscale" ? `"grayscale(1)"` : filter === "b&w" ? `"grayscale(1) contrast(1.2)"` : `"none"`;

  let c = `// ── Avatar ──\n\n`;
  c += `interface AvatarProps {\n`;
  c += `  src?: string;\n`;
  c += `  alt?: string;\n`;
  c += `  size?: number;\n`;
  c += `  style?: React.CSSProperties;\n`;
  c += `}\n\n`;

  c += `export function Avatar({ src, alt, size = 40, style }: AvatarProps) {\n`;
  c += `  return (\n`;
  c += `    <div style={{\n`;
  c += `      width: size, height: size,\n`;
  c += `      borderRadius: ${borderRadius},\n`;
  c += `      overflow: "hidden",\n`;
  if (hasBdr) c += `      border: "${bw}px solid var(--border-color)",\n`;
  if (filter !== "color") c += `      filter: ${filterCSS},\n`;
  c += `      background: "var(--color-surface)",\n`;
  c += `      display: "flex", alignItems: "center", justifyContent: "center",\n`;
  c += `      ...style,\n`;
  c += `    }}>\n`;
  c += `      {src ? <img src={src} alt={alt || ""} style={{ width: "100%", height: "100%", objectFit: "cover" }} /> : null}\n`;
  c += `    </div>\n`;
  c += `  );\n`;
  c += `}\n`;

  return c;
}

function generatePrimitivesTSX(s: DesignState): string | null {
  const parts: string[] = [];

  if (visited(s, "comp-Button")) parts.push(generateButtonCode(s));
  if (visited(s, "comp-Text")) parts.push(generateTextCode(s));
  if (visited(s, "comp-Divider")) parts.push(generateDividerCode(s));
  if (visited(s, "comp-Badge")) parts.push(generateBadgeCode(s));
  if (visited(s, "comp-Avatar")) parts.push(generateAvatarCode(s));

  if (parts.length === 0) return null;

  let code = `import React from "react";\n`;
  code += `import "./tokens.css";\n\n`;
  code += parts.join("\n");
  return code;
}

// ── blocks.tsx ──────────────────────────────────────────────────

function generateCardCode(s: DesignState): string {
  const card = comp(s, "Card");
  const orientation = card.orientation || "vertical";
  const ratio = card.thumbnailRatio || "16:9";
  const hover = card.hoverEffect !== false;
  const r = radiusVar(s, "Card");
  const hasBdr = hasBorder(s, "Card");
  const bw = parseInt(s.borderWidth) || 1;
  const [rw, rh] = ratio.split(":").map(Number);

  let c = `// ── Card ──\n\n`;
  c += `interface CardProps {\n`;
  c += `  thumbnail?: string;\n`;
  c += `  title?: string;\n`;
  c += `  caption?: string;\n`;
  c += `  children?: React.ReactNode;\n`;
  c += `  style?: React.CSSProperties;\n`;
  c += `  onClick?: () => void;\n`;
  c += `}\n\n`;

  c += `export function Card({ thumbnail, title, caption, children, style, onClick }: CardProps) {\n`;

  if (orientation === "horizontal") {
    c += `  return (\n`;
    c += `    <div onClick={onClick} style={{\n`;
    c += `      display: "flex", gap: "var(--space-block)",\n`;
    c += `      padding: "var(--space-block)",\n`;
    c += `      background: "var(--color-surface)",\n`;
    c += `      borderRadius: ${r},\n`;
    if (hasBdr) c += `      border: "${bw}px solid var(--border-color)",\n`;
    if (hover) c += `      transition: "all var(--duration) var(--easing)",\n`;
    c += `      cursor: onClick ? "pointer" : "default",\n`;
    c += `      ...style,\n`;
    c += `    }}>\n`;
    c += `      {thumbnail && <div style={{ width: 100, height: ${Math.round(100 * rh / rw)}, borderRadius: "calc(var(--radius) - 4px)", background: \`url(\${thumbnail}) center/cover\`, flexShrink: 0 }} />}\n`;
    c += `      <div>\n`;
    c += `        {title && <div style={{ fontFamily: "var(--font-heading)", fontSize: 15, fontWeight: 600, color: "var(--color-text-primary)", marginBottom: "calc(var(--space-element) / 2)" }}>{title}</div>}\n`;
    c += `        {caption && <div style={{ fontFamily: "var(--font-body)", fontSize: 12, color: "var(--color-text-secondary)" }}>{caption}</div>}\n`;
    c += `        {children}\n`;
    c += `      </div>\n`;
    c += `    </div>\n`;
    c += `  );\n`;
  } else {
    c += `  return (\n`;
    c += `    <div onClick={onClick} style={{\n`;
    c += `      background: "var(--color-surface)",\n`;
    c += `      borderRadius: ${r},\n`;
    if (hasBdr) c += `      border: "${bw}px solid var(--border-color)",\n`;
    c += `      overflow: "hidden",\n`;
    if (hover) c += `      transition: "all var(--duration) var(--easing)",\n`;
    c += `      cursor: onClick ? "pointer" : "default",\n`;
    c += `      ...style,\n`;
    c += `    }}>\n`;
    c += `      {thumbnail && <div style={{ width: "100%", aspectRatio: "${rw}/${rh}", background: \`url(\${thumbnail}) center/cover\` }} />}\n`;
    c += `      <div style={{ padding: "var(--space-block)" }}>\n`;
    c += `        {title && <div style={{ fontFamily: "var(--font-heading)", fontSize: 15, fontWeight: 600, color: "var(--color-text-primary)", marginBottom: "calc(var(--space-element) / 2)" }}>{title}</div>}\n`;
    c += `        {caption && <div style={{ fontFamily: "var(--font-body)", fontSize: 12, color: "var(--color-text-secondary)" }}>{caption}</div>}\n`;
    c += `        {children}\n`;
    c += `      </div>\n`;
    c += `    </div>\n`;
    c += `  );\n`;
  }

  c += `}\n`;
  return c;
}

function generateGalleryCode(s: DesignState): string {
  const gal = comp(s, "Gallery");
  const cols = gal.columns || 3;
  const galStyle = gal.style || "grid";

  let c = `// ── Gallery ──\n\n`;
  c += `interface GalleryProps {\n`;
  c += `  children: React.ReactNode;\n`;
  c += `  style?: React.CSSProperties;\n`;
  c += `}\n\n`;

  c += `export function Gallery({ children, style }: GalleryProps) {\n`;

  if (galStyle === "horizontal-scroll") {
    c += `  return (\n`;
    c += `    <div style={{ display: "flex", gap: "var(--space-block)", overflowX: "auto", ...style }}>\n`;
    c += `      {children}\n`;
    c += `    </div>\n`;
    c += `  );\n`;
  } else if (galStyle === "masonry") {
    c += `  return (\n`;
    c += `    <div style={{ columnCount: ${cols}, columnGap: "var(--space-block)", ...style }}>\n`;
    c += `      {children}\n`;
    c += `    </div>\n`;
    c += `  );\n`;
  } else {
    c += `  return (\n`;
    c += `    <div style={{ display: "grid", gridTemplateColumns: "repeat(${cols}, 1fr)", gap: "var(--space-block)", ...style }}>\n`;
    c += `      {children}\n`;
    c += `    </div>\n`;
    c += `  );\n`;
  }

  c += `}\n`;
  return c;
}

function generateBlocksTSX(s: DesignState): string | null {
  const parts: string[] = [];

  if (visited(s, "comp-Card")) parts.push(generateCardCode(s));
  if (visited(s, "comp-Gallery")) parts.push(generateGalleryCode(s));

  if (parts.length === 0) return null;

  let code = `import React from "react";\n`;
  code += `import "./tokens.css";\n\n`;
  code += parts.join("\n");
  return code;
}

// ── sections.tsx ────────────────────────────────────────────────

function generateNavbarCode(s: DesignState): string {
  const nav = comp(s, "Navbar");
  const layout = nav.layout || "logo-left";
  const transparent = nav.transparent;
  const r = radiusVar(s, "Navbar");

  let c = `// ── Navbar ──\n\n`;
  c += `interface NavbarProps {\n`;
  c += `  logo?: React.ReactNode;\n`;
  c += `  links?: { label: string; href: string }[];\n`;
  c += `  cta?: { label: string; href: string };\n`;
  c += `  style?: React.CSSProperties;\n`;
  c += `}\n\n`;

  c += `export function Navbar({ logo = "Logo", links = [], cta, style }: NavbarProps) {\n`;

  if (layout === "hamburger-only") {
    c += `  return (\n`;
    c += `    <nav style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "var(--space-inline-y) var(--space-inline-x)", background: ${transparent ? '"transparent"' : '"var(--color-surface)"'}, borderRadius: ${r}, ${hasBorder(s, "Navbar") ? `border: "${parseInt(s.borderWidth) || 1}px solid var(--border-color)", ` : ""}...style }}>\n`;
    c += `      <div style={{ fontFamily: "var(--font-heading)", fontSize: 14, fontWeight: 600, color: "var(--color-text-primary)" }}>{logo}</div>\n`;
    c += `      <button style={{ fontSize: 18, color: "var(--color-text-primary)", background: "none", border: "none", cursor: "pointer" }}>☰</button>\n`;
    c += `    </nav>\n`;
    c += `  );\n`;
  } else if (layout === "centered") {
    c += `  return (\n`;
    c += `    <nav style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "var(--space-element)", padding: "var(--space-inline-y) var(--space-inline-x)", background: ${transparent ? '"transparent"' : '"var(--color-surface)"'}, borderRadius: ${r}, ${hasBorder(s, "Navbar") ? `border: "${parseInt(s.borderWidth) || 1}px solid var(--border-color)", ` : ""}...style }}>\n`;
    c += `      <div style={{ fontFamily: "var(--font-heading)", fontSize: 14, fontWeight: 600, color: "var(--color-text-primary)" }}>{logo}</div>\n`;
    c += `      <div style={{ display: "flex", gap: "var(--space-block)", alignItems: "center" }}>\n`;
    c += `        {links.map(l => <a key={l.href} href={l.href} style={{ fontFamily: "var(--font-body)", fontSize: 12, color: "var(--color-text-secondary)", textDecoration: "none" }}>{l.label}</a>)}\n`;
    c += `        {cta && <a href={cta.href} style={{ padding: "var(--space-inline-y) var(--space-inline-x)", background: "var(--color-accent)", color: "#fff", borderRadius: "var(--radius)", fontSize: 11, fontFamily: "var(--font-body)", fontWeight: 500, textDecoration: "none" }}>{cta.label}</a>}\n`;
    c += `      </div>\n`;
    c += `    </nav>\n`;
    c += `  );\n`;
  } else {
    // logo-left (default)
    c += `  return (\n`;
    c += `    <nav style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "var(--space-inline-y) var(--space-inline-x)", background: ${transparent ? '"transparent"' : '"var(--color-surface)"'}, borderRadius: ${r}, ${hasBorder(s, "Navbar") ? `border: "${parseInt(s.borderWidth) || 1}px solid var(--border-color)", ` : ""}...style }}>\n`;
    c += `      <div style={{ fontFamily: "var(--font-heading)", fontSize: 14, fontWeight: 600, color: "var(--color-text-primary)" }}>{logo}</div>\n`;
    c += `      <div style={{ display: "flex", gap: "var(--space-block)", alignItems: "center" }}>\n`;
    c += `        {links.map(l => <a key={l.href} href={l.href} style={{ fontFamily: "var(--font-body)", fontSize: 12, color: "var(--color-text-secondary)", textDecoration: "none" }}>{l.label}</a>)}\n`;
    c += `        {cta && <a href={cta.href} style={{ padding: "var(--space-inline-y) var(--space-inline-x)", background: "var(--color-accent)", color: "#fff", borderRadius: "var(--radius)", fontSize: 11, fontFamily: "var(--font-body)", fontWeight: 500, textDecoration: "none" }}>{cta.label}</a>}\n`;
    c += `      </div>\n`;
    c += `    </nav>\n`;
    c += `  );\n`;
  }

  c += `}\n`;
  return c;
}

function generateHeroCode(s: DesignState): string {
  const hero = comp(s, "Hero");
  const vt = hero.visualType || "illustration";
  const r = radiusVar(s, "Hero");

  let c = `// ── Hero ──\n`;
  if (hero.visualNotes) c += `// Visual notes: ${hero.visualNotes}\n`;
  c += `// Visual type: ${vt}\n\n`;

  c += `interface HeroProps {\n`;
  c += `  title: string;\n`;
  c += `  subtitle?: string;\n`;
  c += `  primaryAction?: { label: string; href: string };\n`;
  c += `  secondaryAction?: { label: string; href: string };\n`;
  c += `  visual?: React.ReactNode;\n`;
  c += `  style?: React.CSSProperties;\n`;
  c += `}\n\n`;

  c += `export function Hero({ title, subtitle, primaryAction, secondaryAction, visual, style }: HeroProps) {\n`;
  c += `  return (\n`;
  c += `    <div style={{ background: "var(--color-bg)", borderRadius: ${r}, ${hasBorder(s, "Hero") ? `border: "${parseInt(s.borderWidth) || 1}px solid var(--border-color)", ` : ""}padding: "var(--space-content)", display: "flex", gap: "var(--space-block)", alignItems: "center", ...style }}>\n`;
  c += `      <div style={{ flex: 1 }}>\n`;
  c += `        <h1 style={{ fontFamily: "var(--font-heading)", fontSize: 22, fontWeight: 700, color: "var(--color-text-primary)", lineHeight: 1.2, margin: "0 0 var(--space-element)" }}>{title}</h1>\n`;
  c += `        {subtitle && <p style={{ fontFamily: "var(--font-body)", fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.6, margin: "0 0 var(--space-block)" }}>{subtitle}</p>}\n`;
  c += `        <div style={{ display: "flex", gap: "var(--space-element)" }}>\n`;
  c += `          {primaryAction && <a href={primaryAction.href} style={{ padding: "var(--space-inline-y) var(--space-inline-x)", background: "var(--color-accent)", color: "#fff", borderRadius: "var(--radius)", fontSize: 12, fontFamily: "var(--font-body)", fontWeight: 500, textDecoration: "none" }}>{primaryAction.label}</a>}\n`;
  c += `          {secondaryAction && <a href={secondaryAction.href} style={{ padding: "var(--space-inline-y) var(--space-inline-x)", border: "1px solid var(--border-color)", color: "var(--color-text-secondary)", borderRadius: "var(--radius)", fontSize: 12, fontFamily: "var(--font-body)", textDecoration: "none" }}>{secondaryAction.label}</a>}\n`;
  c += `        </div>\n`;
  c += `      </div>\n`;
  if (vt !== "none") {
    c += `      {visual && <div style={{ width: 120, height: 90, borderRadius: "var(--radius)", overflow: "hidden", flexShrink: 0 }}>{visual}</div>}\n`;
  }
  c += `    </div>\n`;
  c += `  );\n`;
  c += `}\n`;

  return c;
}

function generateFooterCode(s: DesignState): string {
  const ft = comp(s, "Footer");
  const structure = ft.structure || "multi-column";
  const newsletter = ft.hasNewsletter;
  const r = radiusVar(s, "Footer");

  let c = `// ── Footer ──\n\n`;
  c += `interface FooterProps {\n`;
  c += `  logo?: React.ReactNode;\n`;
  c += `  columns?: { title: string; links: { label: string; href: string }[] }[];\n`;
  if (newsletter) c += `  onSubscribe?: (email: string) => void;\n`;
  c += `  style?: React.CSSProperties;\n`;
  c += `}\n\n`;

  c += `export function Footer({ logo = "Logo", columns = [], ${newsletter ? "onSubscribe, " : ""}style }: FooterProps) {\n`;
  c += `  return (\n`;
  c += `    <footer style={{ background: "var(--color-bg)", borderRadius: ${r}, ${hasBorder(s, "Footer") ? `border: "${parseInt(s.borderWidth) || 1}px solid var(--border-color)", ` : ""}padding: "var(--space-content)", ...style }}>\n`;

  if (structure === "simple") {
    c += `      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>\n`;
    c += `        <span style={{ fontFamily: "var(--font-heading)", fontSize: 13, fontWeight: 600, color: "var(--color-text-primary)" }}>{logo}</span>\n`;
    c += `        <span style={{ fontFamily: "var(--font-body)", fontSize: 11, color: "var(--color-text-secondary)" }}>© {new Date().getFullYear()} Company</span>\n`;
    c += `      </div>\n`;
  } else {
    c += `      <div style={{ display: "flex", gap: "var(--space-content)", marginBottom: "var(--space-block)" }}>\n`;
    c += `        {columns.map(col => (\n`;
    c += `          <div key={col.title} style={{ flex: 1 }}>\n`;
    c += `            <div style={{ fontFamily: "var(--font-body)", fontSize: 11, fontWeight: 600, color: "var(--color-text-primary)", marginBottom: "var(--space-element)" }}>{col.title}</div>\n`;
    c += `            {col.links.map(l => <a key={l.href} href={l.href} style={{ display: "block", fontFamily: "var(--font-body)", fontSize: 11, color: "var(--color-text-secondary)", marginBottom: "calc(var(--space-element) / 2)", textDecoration: "none" }}>{l.label}</a>)}\n`;
    c += `          </div>\n`;
    c += `        ))}\n`;
    c += `      </div>\n`;
    if (newsletter) {
      c += `      <div style={{ display: "flex", gap: "var(--space-element)", marginBottom: "var(--space-block)" }}>\n`;
      c += `        <input placeholder="Enter your email" style={{ flex: 1, padding: "var(--space-inline-y) var(--space-inline-x)", border: "1px solid var(--border-color)", borderRadius: "var(--radius)", fontFamily: "var(--font-body)", fontSize: 11, color: "var(--color-text-secondary)", background: "transparent" }} />\n`;
      c += `        <button style={{ padding: "var(--space-inline-y) var(--space-inline-x)", background: "var(--color-accent)", color: "#fff", borderRadius: "var(--radius)", fontSize: 11, fontFamily: "var(--font-body)", fontWeight: 500, border: "none", cursor: "pointer" }}>Subscribe</button>\n`;
      c += `      </div>\n`;
    }
    c += `      <div style={{ borderTop: "1px solid var(--border-color)", paddingTop: "var(--space-element)", fontFamily: "var(--font-body)", fontSize: 10, color: "var(--color-text-secondary)", opacity: 0.6 }}>© {new Date().getFullYear()} Company. All rights reserved.</div>\n`;
  }

  c += `    </footer>\n`;
  c += `  );\n`;
  c += `}\n`;

  return c;
}

function generateCTACode(s: DesignState): string {
  const cta = comp(s, "CTA");
  const structure = cta.structure || "centered";
  const r = radiusVar(s, "CTA");

  let c = `// ── CTA ──\n\n`;
  c += `interface CTAProps {\n`;
  c += `  title: string;\n`;
  c += `  subtitle?: string;\n`;
  c += `  action: { label: string; href: string };\n`;
  c += `  style?: React.CSSProperties;\n`;
  c += `}\n\n`;

  c += `export function CTA({ title, subtitle, action, style }: CTAProps) {\n`;

  const isBg = structure === "with-background";
  const isLR = structure === "left-text-right-button";

  c += `  return (\n`;
  c += `    <div style={{\n`;
  c += `      background: ${isBg ? '"var(--color-accent)"' : '"var(--color-surface)"'},\n`;
  c += `      borderRadius: ${r},\n`;
  if (hasBorder(s, "CTA")) c += `      border: "${parseInt(s.borderWidth) || 1}px solid ${isBg ? 'var(--color-accent)' : 'var(--border-color)'}",\n`;
  c += `      padding: "var(--space-content)",\n`;
  c += `      display: "flex",\n`;
  c += `      flexDirection: ${isLR ? '"row"' : '"column"'},\n`;
  c += `      alignItems: "center",\n`;
  if (isLR) c += `      justifyContent: "space-between",\n`;
  else c += `      justifyContent: "center", textAlign: "center" as const,\n`;
  c += `      gap: "var(--space-block)",\n`;
  c += `      ...style,\n`;
  c += `    }}>\n`;
  c += `      <div>\n`;
  c += `        <div style={{ fontFamily: "var(--font-heading)", fontSize: 17, fontWeight: 700, color: ${isBg ? '"#fff"' : '"var(--color-text-primary)"'}, marginBottom: "calc(var(--space-element) / 2)" }}>{title}</div>\n`;
  c += `        {subtitle && <div style={{ fontFamily: "var(--font-body)", fontSize: 12, color: ${isBg ? '"rgba(255,255,255,0.8)"' : '"var(--color-text-secondary)"'} }}>{subtitle}</div>}\n`;
  c += `      </div>\n`;
  c += `      <a href={action.href} style={{ padding: "var(--space-inline-y) var(--space-inline-x)", background: ${isBg ? '"#fff"' : '"var(--color-accent)"'}, color: ${isBg ? '"var(--color-accent)"' : '"#fff"'}, borderRadius: "var(--radius)", fontSize: 12, fontFamily: "var(--font-body)", fontWeight: 500, textDecoration: "none", flexShrink: 0 }}>{action.label}</a>\n`;
  c += `    </div>\n`;
  c += `  );\n`;
  c += `}\n`;

  return c;
}

function generateSectionsTSX(s: DesignState): string | null {
  const parts: string[] = [];

  if (visited(s, "comp-Navbar")) parts.push(generateNavbarCode(s));
  if (visited(s, "comp-Hero")) parts.push(generateHeroCode(s));
  if (visited(s, "comp-Footer")) parts.push(generateFooterCode(s));
  if (visited(s, "comp-CTA")) parts.push(generateCTACode(s));

  if (parts.length === 0) return null;

  let code = `import React from "react";\n`;
  code += `import "./tokens.css";\n\n`;
  code += parts.join("\n");
  return code;
}

// ── zip & download ──────────────────────────────────────────────

export async function generateAndDownload(state: DesignState): Promise<void> {
  const zip = new JSZip();
  const folder = zip.folder("design-system")!;

  // Always generate
  folder.file("CLAUDE.md", generateClaudeMD(state));
  folder.file("tokens.css", generateTokensCSS(state));
  folder.file("tokens.ts", generateTokensTS(state));

  // Conditionally generate
  const primitives = generatePrimitivesTSX(state);
  if (primitives) folder.file("primitives.tsx", primitives);

  const blocks = generateBlocksTSX(state);
  if (blocks) folder.file("blocks.tsx", blocks);

  const sections = generateSectionsTSX(state);
  if (sections) folder.file("sections.tsx", sections);

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${(state.projectName || "design-system").toLowerCase().replace(/\s+/g, "-")}-components.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
